### PR TITLE
Documented existing codebase and modules in [octoffers/platforms]

### PR DESCRIPTION
**Pull request by danieltayal07**
added a few pointers in _index.md
created djinni.md and added documentation about it
added pointers in drivers.md 
created profile.md and added documentation about it

If the contributions are found useful, i would love to see it merged!
Thank You for the opportunity!! ❤️

### CODE REVIEW

**Comment by webgtx** [comment]
Hey @danieltayal07, first of all thank you for your effort.
Don't take it personally, but did you use an AI chatbot to generate most of this content? :shipit:

**Comment by webgtx** [comment]
I don't mind utilizing AI, but the problem is that the content is rather bloated.

**Comment by danieltayal07** [comment]
I used chatgpt to add the extra information

First i sent all the code to chatgpt and asked to explain me what does each and every line do, after that i wrote a summary for each in my words and then i asked it to improve it and increase it.

I knew it is very repetitive and long 
I can shorten it without AI cause i khow what Octoffers do now.

If possible i will do that by the end of the day and commit the changes.

Thank you for understanding sir and apologies

**Comment by danieltayal07** [comment]
Hii @webgtx sir hope you are good

this time i have tried not to use AI for help rather i tried removing the bloated content myself from the files,
please have a look at it when available and give feedback.

Thank You 🫶

**Comment by webgtx** [comment]
@danieltayal07, most of the text still generated.
Regarding documentation for djinni driver: You don't have to explain line by line code of the each method. You have to understand the codebase, and give the instructions for the user on how to use it rather then stating that you're importing *os libraries* for OS operations.

I tried to set you an example [here](https://github.com/init64/octoffers.docs/pull/2/commits/a908c36cb2ee7f6630ae01f7308740ccb0ed7535), try to do the same for the `apply` method.

You can also look into [this](https://python-prompt-toolkit.readthedocs.io/en/3.0.20/) documentation for an example.

**Pull request closed without merging**
